import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BadgeCheck, Bookmark, Building2, ChartNoAxesCombined, Code2, Globe2, PenTool, Play, Quote, Search, Shapes, ShieldCheck, UserRound, UsersRound, ArrowUpRight, MapPin, Menu, X, Mail, Send, type LucideIcon } from 'lucide-react';
import { site } from './content';
import './styles.css';
const icons: Record<string, LucideIcon> = {'building-2':Building2,'users-round':UsersRound,'badge-check':BadgeCheck,'globe-2':Globe2,'pen-tool':PenTool,'code-2':Code2,shapes:Shapes,play:Play,'chart-no-axes-combined':ChartNoAxesCombined,'shield-check':ShieldCheck};
const pages=[['/','Home'],['/about','About'],['/services','Services'],['/projects','Projects'],['/leadership','Leadership'],['/clients','Clients'],['/contact','Contact Us']] as const;
const Label=({children}:{children:React.ReactNode})=><p className="label">{children}</p>;
const Link=({to,children,className=''}:{to:string;children:React.ReactNode;className?:string})=><a className={className} href={to}>{children}</a>;
const Button=({children,solid=false,href='/contact'}:{children:React.ReactNode;solid?:boolean;href?:string})=><Link to={href} className={`button ${solid?'button-solid':''}`}>{children}</Link>;
function Header({path}:{path:string}){const [open,setOpen]=useState(false);useEffect(()=>setOpen(false),[path]);return <header><div className="announcement"><span>{site.status}</span><a href="mailto:studio@ghreatness.io">studio@ghreatness.io</a></div><nav><Link className="wordmark" to="/">GHREATNESSLABS</Link><div className="navicons"><button aria-label={open?'Close navigation':'Open navigation'} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><a aria-label="Search services" href="/services"><Search/></a><a aria-label="Saved work" href="/projects"><Bookmark/></a><a aria-label="Contact" href="/contact"><UserRound/></a></div></nav>{open&&<div className="nav-drawer"><span className="label">Navigate</span>{pages.map(([to,name])=><Link key={to} to={to} className={path===to?'active':''}>{name}</Link>)}</div>}</header>}
function Stats(){return <section className="stats">{site.stats.map(([tag,num,caption,icon])=>{const Icon=icons[icon];return <article key={tag}><span className="icon-badge"><Icon/></span><div><strong>{num}</strong><p>{tag}<span>{caption}</span></p></div></article>})}</section>}
function SectionHead({label,title,accent,copy}:{label:string;title:string;accent?:string;copy?:string}){return <><Label>{label}</Label><h1 className="section-heading">{title} {accent&&<em>{accent}</em>}</h1>{copy&&<p className="section-intro">{copy}</p>}</>}
function Capabilities({limit}:{limit?:number}){return <div className="cap-grid">{site.capabilities.slice(0,limit).map(([spec,title,desc,tags,icon],index)=>{const Icon=icons[icon];return <article className={`cap ${index%2?'cap-dark':''}`} key={title}><div className="cap-header"><span className="icon-badge"><Icon/></span><small>{spec}</small><span className="cap-index">{String(index+1).padStart(2,'0')}</span></div><h3>{title}</h3><p>{desc}</p><div className="tags">{tags.map(tag=><span key={tag}>{tag}</span>)}</div></article>})}</div>}
function Ventures({limit}:{limit?:number}){return <div className="venture-grid">{site.ventures.slice(0,limit).map(([name,cat,desc,detail],i)=><article className={`venture v${i}`} key={name}><div className="venture-visual"><span className="venture-badge">{cat}</span><span className="venture-mark"><i/><b/></span></div><div className="venture-body"><h3>{name}</h3><p>{desc}</p>{detail&&<p className="venture-detail">{detail}</p>}<Link to="/contact">Discuss this kind of work <ArrowUpRight/></Link></div></article>)}</div>}
function Testimonials({limit}:{limit?:number}){return <div className="trust-grid">{site.testimonials.slice(0,limit).map(([where,quote,name,title])=>{const initials=name.split(' ').map(x=>x[0]).join('');return <blockquote key={name}><Quote className="testimonial-quote"/><small>{where}</small><p>{quote}</p><footer><span className="testimonial-avatar">{initials}</span><span><b>{name}</b><small>{title}</small></span></footer></blockquote>})}</div>}
function Home(){return <><section className="hero section"><div className="hero-copy"><SectionHead label={site.hero.eyebrow} title={site.hero.title.primary} accent={site.hero.title.secondary} copy={site.hero.body}/><div className="actions"><Button solid>Book a consultation</Button><Button href="/projects">Explore case studies</Button></div></div><div className="hero-aside"><div className="infrastructure-mark"><span className="infrastructure-ring infrastructure-ring-outer"/><span className="infrastructure-ring infrastructure-ring-middle"/><span className="infrastructure-dot"/><span className="infrastructure-badge">Infrastructure</span></div><div className="dispatch"><b>Studio at a glance</b><p>Current availability <strong>Q2 projects</strong></p><p>Based in <strong>Lagos, Nigeria</strong></p><p>Working with <strong>Global teams</strong></p></div></div></section><Stats/><section className="section soft-section"><SectionHead label="Practice areas" title="Core capabilities" accent="for ambitious teams." copy="Cross-disciplinary expertise for organizations that need a system, not just a surface."/><Capabilities limit={3}/><Button href="/services">View all services</Button></section><section className="section"><SectionHead label="Selected ventures" title="Products with" accent="purpose."/><Ventures limit={3}/><Button href="/projects">View all projects</Button></section><section className="section soft-section"><SectionHead label="Client perspectives" title="Trusted by teams" accent="around the world."/><Testimonials limit={2}/><Button href="/clients">Read all perspectives</Button></section></>}
function About(){return <><section className="section page-intro"><SectionHead label="About GhreatnessLabs" title="Built in Lagos for" accent="important work." copy="We are an independent digital studio for teams that need clarity, craft, and capable delivery in equal measure."/><div className="story-grid"><article><h3>Our story</h3><p>Founded in Lagos in 2024, GhreatnessLabs began with a simple belief: the digital systems African and global teams rely on should be as considered as their ambition.</p></article><article className="story-dark"><h3>Our mission</h3><p>Make high-impact work more coherent—bringing strategy, identity, product design, engineering, and infrastructure into one accountable studio practice.</p></article><article><h3>What we do</h3><p>We partner with founders, institutions, and established teams to create products, brands, and operational foundations made to endure.</p></article></div></section><Stats/></>}
function Services(){return <section className="section soft-section page-intro"><SectionHead label="Practice areas" title="Full-spectrum capabilities" accent="under one roof." copy="Each engagement is shaped around the work that will make the greatest difference—from a first product direction to a connected brand and technology system."/><Capabilities/></section>}
function Projects(){return <section className="section page-intro"><SectionHead label="Portfolio" title="Ventures and case studies" accent="made to move." copy="We use systems thinking to make products, platforms, and brands more useful in the real world."/><Ventures/></section>}
function Leadership(){return <section className="section soft-section page-intro"><SectionHead label="Leadership" title="A small team for" accent="high-stakes work." copy="Senior thinking stays close to the brief, the details, and the people making decisions."/><div className="team-grid">{site.team.map(([name,role,bio],i)=><article className={`team-card ${i%2?'team-dark':''}`} key={name}><span className="team-avatar">{name.split(' ').map(x=>x[0]).join('')}</span><div><h3>{name}</h3><small>{role}</small><p>{bio}</p></div></article>)}</div></section>}
function Clients(){return <section className="section page-intro"><SectionHead label="Clients" title="Partners with" accent="a point of view." copy="We work with organizations that see design and technology as a meaningful advantage."/><div className="client-list">{site.clients.map(client=><span key={client}>{client}</span>)}</div><div className="testimonials-section"><SectionHead label="Client perspectives" title="Trusted across" accent="markets and moments."/><Testimonials/></div></section>}
function Contact(){return <section className="section soft-section page-intro"><SectionHead label="Contact us" title="Start the" accent="conversation." copy="Tell us what you are building. We will reply with the right next step."/><div className="contact-grid"><form onSubmit={e=>e.preventDefault()}><label>Name<input required name="name" placeholder="Your name"/></label><label>Email<input required type="email" name="email" placeholder="you@company.com"/></label><label>Company<input name="company" placeholder="Company or organization"/></label><label>Service category<select name="service"><option>Choose a service</option>{site.capabilities.map(([,title])=><option key={title}>{title}</option>)}</select></label><label className="form-message">Message<textarea required name="message" placeholder="A little about the opportunity" rows={5}/></label><button className="button button-solid" type="submit">Send inquiry <Send/></button></form><aside className="contact-details"><span className="icon-badge"><Mail/></span><h3>Studio contact</h3><a href="mailto:studio@ghreatness.io">studio@ghreatness.io</a><span className="icon-badge"><MapPin/></span><h3>Lagos HQ</h3><p>Victoria Island<br/>Lagos, Nigeria</p></aside></div></section>}
function Footer(){return <footer><section className="cta"><Label>Start a conversation</Label><h2 className="section-heading">Let us build your <em>next important thing.</em></h2><p>Start with a confidential, no-obligation consultation.</p><div className="actions"><Button solid>Book a consultation</Button><a className="button" href="mailto:studio@ghreatness.io">studio@ghreatness.io</a></div></section><div className="footer-grid"><div><b className="wordmark">GHREATNESSLABS</b><p>Digital systems and brand experiences built from Lagos for the world.</p></div><div className="footer-links">{pages.slice(1).map(([to,name])=><Link key={to} to={to}>{name}</Link>)}</div><div><small>Lagos HQ</small><p className="footer-address"><MapPin/> <span>Victoria Island<br/>Lagos, Nigeria</span></p></div></div><div className="legal"><span>© 2026 GHREATNESSLABS. All rights reserved.</span><span>Privacy · Terms · Accessibility</span></div></footer>}
function App(){const [path,setPath]=useState(location.pathname);useEffect(()=>{const go=()=>setPath(location.pathname);addEventListener('popstate',go);return()=>removeEventListener('popstate',go)},[]);useEffect(()=>{const click=(e:MouseEvent)=>{const a=(e.target as Element).closest('a[href^="/"]') as HTMLAnchorElement|null;if(a){e.preventDefault();history.pushState({},'',a.pathname);setPath(a.pathname);scrollTo(0,0)}};addEventListener('click',click);return()=>removeEventListener('click',click)},[]);const Page=({'/':Home,'/about':About,'/services':Services,'/projects':Projects,'/leadership':Leadership,'/clients':Clients,'/contact':Contact}[path]||Home);return <><Header path={path}/><main><Page/></main><Footer/></>};createRoot(document.getElementById('root')!).render(<App/>);
