import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Bookmark, Search, UserRound, ArrowUpRight } from 'lucide-react';
import { site } from './content';
import './styles.css';

const Label=({children}:{children:React.ReactNode})=><p className="label"><i />{children}</p>;
const Button=({children,solid=false}:{children:React.ReactNode;solid?:boolean})=><a href="#contact" className={`button ${solid?'button-solid':''}`}>{children}</a>;
function Header(){return <header><div className="topbar"><span>■ GREATNESSLABS // LAGOS NODE</span><span>[06°27'N 03°23'E]</span></div><div className="status">{site.status}</div><nav><a className="wordmark" href="#top">GREATNESSLABS</a><div className="navicons"><a aria-label="Search" href="#capabilities"><Search/></a><a aria-label="Saved work" href="#ventures"><Bookmark/></a><a aria-label="Contact account" href="#contact"><UserRound/></a></div></nav></header>}
function Hero(){return <section id="top" className="hero section"><div className="hero-copy fade"><Label>{site.hero.eyebrow}</Label><h1>{site.hero.title[0]}<br/><em>{site.hero.title[1]}</em><br/>{site.hero.title[2]}</h1><p className="intro">{site.hero.body}</p><div className="actions"><Button solid>Book a Consultation</Button><Button>Explore Case Studies →</Button></div></div><div className="hero-aside"><div className="architecture" role="img" aria-label="Abstract monochrome architectural infrastructure visualization"><span>INFRASTRUCTURE<br/>VISUALIZATION</span></div><div className="dispatch"><b>LIVE DISPATCH // LAGOS HQ</b><p>BUILD STAGE <strong>DEPLOYING</strong></p><p>EDGE LATENCY <strong>18 MS</strong></p><p>ACTIVE CLIENTS <strong>124</strong></p></div><button className="assistant">● AI ASSISTANT</button></div></section>}
function Stats(){return <section className="stats">{site.stats.map(([tag,num,caption])=><article key={tag}><small>{tag}</small><strong>{num}</strong><p>{caption}</p></article>)}</section>}
function Capabilities(){return <section id="capabilities" className="section"><Label>PRACTICE AREAS // STUDIO DISCIPLINE</Label><h2>Core capabilities <em>matrix</em></h2><p className="section-intro">Cross-disciplinary deployments for organizations that need a system, not a surface.</p><div className="cap-grid">{site.capabilities.map(([n,spec,title,desc,tags])=><article className="cap" key={title}><small>{n} &nbsp; SPEC: {spec}</small><h3>{title}</h3><p>{desc}</p><div>{tags.map(tag=><span key={tag}>{tag}</span>)}</div></article>)}</div></section>}
function Telemetry(){return <section className="telemetry section"><Label>TELEMETRY // THROUGHPUT METRICS</Label><h2>Continuous <em>deployment</em> cycle</h2><p className="section-intro">Operational clarity from first brief through post-launch maintenance.</p><svg viewBox="0 0 900 190" aria-label="Continuous deployment throughput line chart" role="img"><path className="chart-grid" d="M0 40H900M0 95H900M0 150H900"/><path className="chart-line" d="M0 145 C55 130 70 48 140 75 S245 155 300 95 S390 28 465 74 S540 153 620 105 S705 25 785 68 S850 130 900 35"/><g className="dots"><circle cx="140" cy="75" r="5"/><circle cx="300" cy="95" r="5"/><circle cx="465" cy="74" r="5"/><circle cx="620" cy="105" r="5"/><circle cx="785" cy="68" r="5"/></g></svg><div className="chart-meta"><span>TIMESTAMP // 09.23.26</span><span>LATENCY // 18MS</span><span>TARGET // 99.98%</span></div></section>}
function Ventures(){return <section id="ventures" className="section"><Label>INTERNAL INCUBATOR // SOFTWARE LABS</Label><h2>Proprietary <em>ventures</em></h2><div className="venture-grid">{site.ventures.map(([tag,name,cat,desc],i)=><article className={`venture v${i}`} key={name}><div className="venture-visual"><span>{tag}</span></div><div className="venture-body"><p className="category">{cat}</p><h3>{name}</h3><p>{desc}</p><a href="#contact">[ PROTOCOL SPECS ] <ArrowUpRight/></a></div></article>)}</div></section>}
function Trust(){return <section className="section"><Label>VERIFIED CLIENT CORROBORATION</Label><h2>Global trust consortium</h2><p className="cities">LAGOS · LONDON · NEW YORK</p><div className="trust-grid">{site.testimonials.map(([where,quote,name,title])=><blockquote key={name}><small>{where}</small><p>{quote}</p><footer><b>{name}</b><br/>{title}</footer></blockquote>)}</div></section>}
function Clock(){const [time,setTime]=useState(''); useEffect(()=>{const run=()=>setTime(new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Lagos',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date()));run();const id=setInterval(run,1000);return()=>clearInterval(id)},[]);return <span>{time || '--:--:--'} WAT</span>}
function Footer(){return <footer id="contact"><section className="cta"><Label>[ READY FOR SYSTEM COMMISSIONING ]</Label><h2>Let us build your <em>strategic monument.</em></h2><p>Start with a confidential, no-obligation NDA consultation.</p><div className="actions"><Button solid>Book a Consultation</Button><Button>studio@greatness.io →</Button></div></section><div className="footer-grid"><div><b className="wordmark">GREATNESSLABS</b><p>Digital systems and brand experiences built from Lagos for the world.</p></div><div><small>SOLUTIONS</small><a href="#capabilities">Product Design</a><a href="#capabilities">Engineering</a><a href="#capabilities">Infrastructure</a></div><div><small>STUDIO</small><a href="#ventures">Ventures</a><a href="#capabilities">Practice Areas</a><a href="#top">Journal</a></div><div><small>LAGOS / HQ</small><p>Victoria Island<br/>Lagos, Nigeria</p><div className="clock"><Clock/></div></div></div><div className="legal"><span>© 2026 GREATNESSLABS. ALL RIGHTS RESERVED.</span><span>PRIVACY &nbsp; TERMS &nbsp; ACCESSIBILITY</span></div></footer>}
function App(){return <><Header/><main><Hero/><Stats/><Capabilities/><Telemetry/><Ventures/><Trust/></main><Footer/></>};createRoot(document.getElementById('root')!).render(<App/>);
